name: "Lint PR"

on:
  pull_request_target:
    branches:
      - 'main'
    types:
      - opened
      - edited
      - synchronize
      - auto_merge_enabled
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
