on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Create Release
jobs:      
  release-main:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main

       # The logic below handles the npm publication:
      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        if: ${{ steps.release.outputs.releases_created }}
        with:
          cache: npm
          node-version: '16.16.0'
      - name: Install Dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm ci

      # Release Please has already incremented versions and published tags, so we just
      # need to publish all unpublished versions to NPM here
      # See: https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package
      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npx lerna publish 
