on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Create Release
jobs:      
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main

      - name: Dump context
        env:
          STEPS: ${{ toJson(steps) }}
        run: echo "$STEPS"
          
        # The logic below handles the npm publication:
      - name: Checkout Repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '16.16.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      # Release Please has already incremented versions and published tags, so we just
      # need to publish all unpublished versions to NPM here
      # See: https://github.com/lerna/lerna/tree/main/libs/commands/publish#bump-from-package
      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npx lerna publish from-package --no-push --no-private --yes
